[package]
name = "cli-game"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.16", features = ["derive"] }
# colored = "2.1.0"
crossterm = "0.28.1"
mlua = { version = "0.9.9", features = ["lua54", "vendored"] }
